name: Stop & Start Render Server

on:
  schedule:
    # Runs at 1:00 AM UTC every day (Stop server)
    - cron: "0 1 * * *"
    # Runs at 3:00 AM UTC every day (Start server)
    - cron: "0 3 * * *"

jobs:
  control-render:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Render Backend (at 1 AM)
        if: github.event.schedule == '0 1 * * *'
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cve32rd2ng1s73ccqvog" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      - name: Start Render Backend (at 3 AM)
        if: github.event.schedule == '0 3 * * *'
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cve32rd2ng1s73ccqvog" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
